import org.apache.spark.sql.types.DataTypes;
import org.apache.spark.sql.types.StructType;

import java.util.Map;

public class StructTypes {
    public static final StructType ANB = new StructType()
            .add("id", DataTypes.DoubleType)
            .add("listing_url", DataTypes.StringType)
            .add("scrape_id", DataTypes.DoubleType)
            .add("location", DataTypes.StringType)
            .add("last_scraped", DataTypes.StringType)
            .add("source", DataTypes.StringType)
            .add("name", DataTypes.StringType)
            .add("description", DataTypes.StringType)
            .add("neighborhood_overview", DataTypes.StringType)
            .add("picture_url", DataTypes.StringType)
            .add("host_id", DataTypes.DoubleType)
            .add("host_url", DataTypes.StringType)
            .add("host_name", DataTypes.StringType)
            .add("host_since", DataTypes.StringType)
            .add("host_location", DataTypes.StringType)
            .add("host_about", DataTypes.StringType)
            .add("host_response_time", DataTypes.StringType)
            .add("host_response_rate", DataTypes.StringType)
            .add("host_acceptance_rate", DataTypes.StringType)
            .add("host_is_superhost", DataTypes.StringType)
            .add("host_thumbnail_url", DataTypes.StringType)
            .add("host_picture_url", DataTypes.StringType)
            .add("host_neighbourhood", DataTypes.StringType)
            .add("host_listings_count", DataTypes.DoubleType)
            .add("host_total_listings_count", DataTypes.DoubleType)
            .add("host_verifications", DataTypes.StringType)
            .add("host_has_profile_pic", DataTypes.StringType)
            .add("host_identity_verified", DataTypes.StringType)
            .add("neighbourhood", DataTypes.StringType)
            .add("neighbourhood_cleansed", DataTypes.StringType)
            .add("neighbourhood_group_cleansed", DataTypes.StringType)
            .add("latitude", DataTypes.DoubleType)
            .add("longitude", DataTypes.DoubleType)
            .add("property_type", DataTypes.StringType)
            .add("room_type", DataTypes.StringType)
            .add("accommodates", DataTypes.DoubleType)
            .add("bathrooms", DataTypes.DoubleType)
            .add("bathrooms_text", DataTypes.StringType)
            .add("bedrooms", DataTypes.DoubleType)
            .add("beds", DataTypes.DoubleType)
            .add("amenities", DataTypes.StringType)
            .add("price", DataTypes.DoubleType)
            .add("minimum_nights", DataTypes.DoubleType)
            .add("maximum_nights", DataTypes.DoubleType)
            .add("minimum_minimum_nights", DataTypes.DoubleType)
            .add("maximum_minimum_nights", DataTypes.DoubleType)
            .add("minimum_maximum_nights", DataTypes.DoubleType)
            .add("maximum_maximum_nights", DataTypes.DoubleType)
            .add("minimum_nights_avg_ntm", DataTypes.DoubleType)
            .add("maximum_nights_avg_ntm", DataTypes.DoubleType)
            .add("calendar_updated", DataTypes.StringType)
            .add("has_availability", DataTypes.StringType)
            .add("availability_30", DataTypes.DoubleType)
            .add("availability_60", DataTypes.DoubleType)
            .add("availability_90", DataTypes.DoubleType)
            .add("availability_365", DataTypes.DoubleType)
            .add("calendar_last_scraped", DataTypes.StringType)
            .add("number_of_reviews", DataTypes.DoubleType)
            .add("number_of_reviews_ltm", DataTypes.DoubleType)
            .add("number_of_reviews_l30d", DataTypes.DoubleType)
            .add("first_review", DataTypes.StringType)
            .add("last_review", DataTypes.StringType)
            .add("review_scores_rating", DataTypes.DoubleType)
            .add("review_scores_accuracy", DataTypes.DoubleType)
            .add("review_scores_cleanliness", DataTypes.DoubleType)
            .add("review_scores_checkin", DataTypes.DoubleType)
            .add("review_scores_communication", DataTypes.DoubleType)
            .add("review_scores_location", DataTypes.DoubleType)
            .add("review_scores_value", DataTypes.DoubleType)
            .add("license", DataTypes.StringType)
            .add("instant_bookable", DataTypes.StringType)
            .add("calculated_host_listings_count", DataTypes.LongType)
            .add("calculated_host_listings_count_entire_homes", DataTypes.LongType)
            .add("calculated_host_listings_count_private_rooms", DataTypes.LongType)
            .add("calculated_host_listings_count_shared_rooms", DataTypes.LongType)
            .add("reviews_per_month", DataTypes.DoubleType);

    public static final StructType BOOKING = new StructType()
            .add("Unnamed: 0", DataTypes.LongType)
            .add("Hotels", DataTypes.StringType)
            .add("Prices", DataTypes.StringType)
            .add("Descriptions", DataTypes.StringType)
            .add("Full_Descriptions", DataTypes.StringType);

    public static final StructType OTHER = new StructType()
            .add("Unnamed: 0", DataTypes.LongType)
            .add("Hotel name", DataTypes.StringType)
            .add("Marks", DataTypes.DoubleType)
            .add("Region City", DataTypes.StringType)
            .add("Performances", DataTypes.StringType)
            .add("Reviews", DataTypes.StringType)
            .add("Price", DataTypes.StringType)
            .add("Distances", DataTypes.StringType)
            .add("Discriptions", DataTypes.StringType)
            .add("Stars", DataTypes.LongType)
            .add("Breakfast", DataTypes.StringType)
            .add("Guests reviews:", DataTypes.StringType);

    public static final Map<String, String> PATTERN = Map.of(
            "anb", "/app/data/anb/*.csv",
            "booking", "/app/data/booking/*.csv",
            "other",  "/app/data/other/*.csv"
    );
}
